name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install Dependencies
        run: npm ci

      - name: Build Frontend
        run: npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat >>~/.ssh/config <<END
          Host ec2
            HostName ${{ secrets.EC2_HOST }}
            User ubuntu
            IdentityFile ~/.ssh/deploy_key
            StrictHostKeyChecking no
          END

      - name: Deploy Frontend
        run: |
          ssh ec2 '
            sudo mkdir -p /var/www/media-manager/frontend &&
            sudo chown -R ubuntu:www-data /var/www/media-manager &&
            sudo chmod -R 755 /var/www/media-manager
          '

          rsync -avz --delete \
            --exclude 'node_modules' \
            --exclude '.git' \
            --exclude 'src' \
            --exclude 'public' \
            --exclude 'package.json' \
            --exclude 'package-lock.json' \
            ./build/ ec2:/var/www/media-manager/frontend/

          ssh ec2 'sudo systemctl restart nginx'
